# PANDAS

# Series

In [1]:
import pandas as pd

In [4]:
x=[3,4,5,6,7,8]

var = pd.Series(x)

print(var)

print(type(var))

print(var[2])

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64
<class 'pandas.core.series.Series'>
5

In [7]:
x=[3,4,5,6]

var = pd.Series(x,index=['a','b','c','d'],dtype="float",name="python")

print(var)

a    3.0
b    4.0
c    5.0
d    6.0
Name: python, dtype: float64

In [8]:
dic = {"name" : ['python','c','java'],
      "por":[12,13,14,15],"rank" : [1,4,3,2]}
+
var = pd.Series(dic)

print(var)

name    [python, c, java]
por      [12, 13, 14, 15]
rank         [1, 4, 3, 2]
dtype: object

In [9]:
s = pd.Series(12,index=[1,2,3,4,5,6,7])

print(s)

print(type(s))

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
s1 = pd.Series(12,index=[1,2,3,4,5,6,7])
s2 = pd.Series(12,index=[1,2,3,4])

print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

# Data Frame

In [19]:


l=[1,2,3,4,5,6]

var = pd.DataFrame(l)


print(type(var))

<class 'pandas.core.frame.DataFrame'>

In [23]:
d = {"a":[1,2,3,4,5],"s":[1,2,3,4,5],"d":[1,2,3,4,5]}

var1 = pd.DataFrame(d)

var2 = pd.DataFrame(d,columns=["a"])


print(var1)
print(var2)

print()

print(var1["a"][3])

   a  s  d
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
   a
0  1
1  2
2  3
3  4
4  5

4

In [24]:
list = [[1,2,3,4,5],[11,12,13,14,15]]

var3 = pd.DataFrame(list)

print(var3)

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

# Arithmatic Operators

In [29]:

var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})

var["C"] = var["A"]+var["B"]

var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [35]:
var5 = pd.DataFrame({"A":[10,20,30,40],"B":[15,16,17,18]})

var5["Python"] = var["A"]<=20

var5

    A   B  Python
0  10  15    True
1  20  16    True
2  30  17   False
3  40  18   False

# Insert

In [37]:
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})


var.insert(1,"python",var["A"])


var

   A  python  B
0  1       1  5
1  2       2  6
2  3       3  7
3  4       4  8

In [39]:
var["python_1"] = var["A"][0:3]

var

   A  python  B  python_1
0  1       1  5       1.0
1  2       2  6       2.0
2  3       3  7       3.0
3  4       4  8       NaN

# Delete

In [46]:
var6 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})

var7 =var6.pop("B")

var6

#del var["A"]

#var6

   A
0  1
1  2
2  3
3  4

# Write CSV

In [50]:
dic = pd.DataFrame({"A":[1,2,3,4,5,6],"B":[5,6,7,8,9,10],"C":[11,12,13,14,15,16]})

d=pd.DataFrame(dic)

print(d)

d.to_csv("Test_new.csv",index=False,header=[1,2,3])

   A   B   C
0  1   5  11
1  2   6  12
2  3   7  13
3  4   8  14
4  5   9  15
5  6  10  16

# Read CSV

In [5]:
import pandas as pd

csv_1 = pd.read_csv("C:\\Users\\shara\\Test_new.csv")

csv_1

   1   2   3
0  1   5  11
1  2   6  12
2  3   7  13
3  4   8  14
4  5   9  15
5  6  10  16

In [7]:
csv_2 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",nrows=3)

csv_2

   1  2   3
0  1  5  11
1  2  6  12
2  3  7  13

In [8]:
csv_3 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",usecols=["1"])

csv_3

   1
0  1
1  2
2  3
3  4
4  5
5  6

In [10]:
csv_4 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",skiprows=[2,5])

csv_4

   1   2   3
0  1   5  11
1  3   7  13
2  4   8  14
3  6  10  16

In [11]:
csv_5 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",index_col="1")

csv_5

    2   3
1
1   5  11
2   6  12
3   7  13
4   8  14
5   9  15
6  10  16

In [13]:
csv_6 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",header=2)

csv_6

   2   6  12
0  3   7  13
1  4   8  14
2  5   9  15
3  6  10  16

In [15]:
csv_7 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",names=["col1","col2","col3","col4"])

csv_7

   col1  col2  col3  col4
0     1     2     3   NaN
1     1     5    11   NaN
2     2     6    12   NaN
3     3     7    13   NaN
4     4     8    14   NaN
5     5     9    15   NaN
6     6    10    16   NaN

In [18]:
csv_8 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",header=None,prefix="col")

csv_8

C:\Users\shara\AppData\Local\Temp\ipykernel_6084\794698794.py:1: FutureWarning: The prefix argument has been deprecated and will be removed in a future version. Use a list comprehension on the column names in the future.


  csv_8 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",header=None,prefix="col")

   col0  col1  col2
0     1     2     3
1     1     5    11
2     2     6    12
3     3     7    13
4     4     8    14
5     5     9    15
6     6    10    16

In [21]:
csv_9 = pd.read_csv("C:\\Users\\shara\\Test_new.csv",dtype={"1":"float"})

csv_9

     1   2   3
0  1.0   5  11
1  2.0   6  12
2  3.0   7  13
3  4.0   8  14
4  5.0   9  15
5  6.0  10  16

# Pandas Function

In [14]:
import pandas as pd

csvn1 = pd.read_csv("C:\\Users\\shara\\Test_new.csv")

csvn1

   1   2   3
0  1   5  11
1  2   6  12
2  3   7  13
3  4   8  14
4  5   9  15
5  6  10  16

In [15]:
csvn1.index

RangeIndex(start=0, stop=6, step=1)

In [16]:
csvn1.columns

Index(['1', '2', '3'], dtype='object')

In [17]:
csvn1.describe()

              1          2          3
count  6.000000   6.000000   6.000000
mean   3.500000   7.500000  13.500000
std    1.870829   1.870829   1.870829
min    1.000000   5.000000  11.000000
25%    2.250000   6.250000  12.250000
50%    3.500000   7.500000  13.500000
75%    4.750000   8.750000  14.750000
max    6.000000  10.000000  16.000000

In [19]:
csvn1.head(3)

   1  2   3
0  1  5  11
1  2  6  12
2  3  7  13

In [20]:
csvn1.tail(2)

   1   2   3
4  5   9  15
5  6  10  16

In [21]:
csvn1[:2]

   1  2   3
0  1  5  11
1  2  6  12

In [22]:
print(type(csvn1))

<class 'pandas.core.frame.DataFrame'>

In [23]:
csvn1.index.array

<PandasArray>
[0, 1, 2, 3, 4, 5]
Length: 6, dtype: int64

In [24]:
csvn1.to_numpy()

array([[ 1,  5, 11],
       [ 2,  6, 12],
       [ 3,  7, 13],
       [ 4,  8, 14],
       [ 5,  9, 15],
       [ 6, 10, 16]], dtype=int64)

In [25]:
import numpy as np

v = np.asarray(csvn1)

v

array([[ 1,  5, 11],
       [ 2,  6, 12],
       [ 3,  7, 13],
       [ 4,  8, 14],
       [ 5,  9, 15],
       [ 6, 10, 16]], dtype=int64)

In [27]:
csvn1.sort_index(axis=0,ascending=False)

   1   2   3
5  6  10  16
4  5   9  15
3  4   8  14
2  3   7  13
1  2   6  12
0  1   5  11

In [29]:
csvn1["1"][0]="python"

csvn1

        1   2   3
0  python   5  11
1       2   6  12
2       3   7  13
3       4   8  14
4       5   9  15
5       6  10  16

In [30]:
csvn1.loc[2,"1"]="Python"

csvn1

        1   2   3
0  python   5  11
1       2   6  12
2  Python   7  13
3       4   8  14
4       5   9  15
5       6  10  16

In [31]:
csvn1.loc[[2,3],["1","2"]]

        1  2
2  Python  7
3       4  8

In [35]:
csvn1.loc[:,["1","2"]]

        1   2
0  python   5
1       2   6
2  Python   7
3       4   8
4       5   9
5       6  10

In [36]:

csvn1.loc[[2,3],:]

        1  2   3
2  Python  7  13
3       4  8  14

In [38]:
csvn1.iloc[0,2]

11

In [39]:
csvn1.drop("1",axis=1)

    2   3
0   5  11
1   6  12
2   7  13
3   8  14
4   9  15
5  10  16

# dropna & fillna

In [41]:
drop = pd.DataFrame({"Name":["a","b","c","d","e","f"],"Age":[15,15,45,65,23,20],"C":["M","F","M","M","F","F"]})

f=pd.DataFrame(drop)

print(f)

f.to_csv("DropFill.csv",index=False)

  Name  Age  C
0    a   15  M
1    b   15  F
2    c   45  M
3    d   65  M
4    e   23  F
5    f   20  F

In [42]:
import pandas as pd

In [46]:
var =pd.read_csv("C:\\Users\\shara\\DropFill.csv")
var

  Name   Age    C
0    a  15.0    M
1    b   NaN    F
2    c  45.0    M
3    d  65.0    M
4    e  23.0  NaN
5    f   NaN    F

In [48]:
var.dropna()

  Name   Age  C
0    a  15.0  M
2    c  45.0  M
3    d  65.0  M

In [49]:
var.dropna(axis=1)

  Name
0    a
1    b
2    c
3    d
4    e
5    f

In [51]:
var.dropna(how="any")  #We can give "all" also

  Name   Age  C
0    a  15.0  M
2    c  45.0  M
3    d  65.0  M

In [54]:
var.dropna(subset=["Age"])

#Removes null valuefrom specified coloumn

  Name   Age    C
0    a  15.0    M
2    c  45.0    M
3    d  65.0    M
4    e  23.0  NaN

In [57]:
var.dropna(inplace=True)
var

  Name   Age  C
0    a  15.0  M
2    c  45.0  M
3    d  65.0  M

In [60]:
var.dropna(thresh=3)

#removes rows based on thenumber of null values  we provided

  Name   Age  C
0    a  15.0  M
2    c  45.0  M
3    d  65.0  M

In [63]:
drop = pd.DataFrame({"Name":["a","b","c","d","e","f"],"Age":[15,15,45,65,23,20],"C":["M","F","M","M","F","F"]})

f=pd.DataFrame(drop)

print(f)

f.to_csv("Fill.csv",index=False)

  Name  Age  C
0    a   15  M
1    b   15  F
2    c   45  M
3    d   65  M
4    e   23  F
5    f   20  F

In [65]:
fil =pd.read_csv("C:\\Users\\shara\\Fill.csv")
fil

  Name   Age    C
0    a   NaN    M
1    b  15.0    F
2  NaN  45.0    M
3    d   NaN    M
4    e  23.0  NaN
5    f  20.0    F

In [66]:
fil.fillna("Sharan")

     Name     Age       C
0       a  Sharan       M
1       b    15.0       F
2  Sharan    45.0       M
3       d  Sharan       M
4       e    23.0  Sharan
5       f    20.0       F

In [67]:
fil.fillna({"Name":"Sharan","Age":"19","C":"M"})

     Name   Age  C
0       a    19  M
1       b  15.0  F
2  Sharan  45.0  M
3       d    19  M
4       e  23.0  M
5       f  20.0  F

In [70]:
fil.fillna(method="ffill")

#method contains two values forward filling(ffill) and backward filling(bfill)

  Name   Age  C
0    a   NaN  M
1    b  15.0  F
2    b  45.0  M
3    d  45.0  M
4    e  23.0  M
5    f  20.0  F

In [74]:
fil.fillna(12,inplace=True)
fil

  Name   Age   C
0    a  12.0   M
1    b  15.0   F
2   12  45.0   M
3    d  12.0   M
4    e  23.0  12
5    f  20.0   F

In [76]:
fil.fillna("python",limit=2)

# Here in this case thevalue "python" is filled uptho 2 rows

  Name   Age   C
0    a  12.0   M
1    b  15.0   F
2   12  45.0   M
3    d  12.0   M
4    e  23.0  12
5    f  20.0   F

# Replace

In [78]:
rep =pd.read_csv("C:\\Users\\shara\\Fill.csv")
rep

  Name  Age  C
0    a   20  M
1    b   15  F
2    c   45  M
3    d   32  M
4    e   23  F
5    f   20  F

In [79]:
rep.replace(to_replace="M",value="Male")

  Name  Age     C
0    a   20  Male
1    b   15     F
2    c   45  Male
3    d   32  Male
4    e   23     F
5    f   20     F

In [81]:
rep.replace(["a","b","c","d","e","f"],1)

   Name  Age  C
0     1   20  M
1     1   15  F
2     1   45  M
3     1   32  M
4     1   23  F
5     1   20  F

In [85]:
rep.replace("[A-Z]","python",regex=True)

  Name  Age       C
0    a   20  python
1    b   15  python
2    c   45  python
3    d   32  python
4    e   23  python
5    f   20  python

In [90]:
rep.replace({"Name":'[A-Z]'},22,regex=True)

  Name  Age  C
0    a   20  M
1    b   15  F
2    c   45  M
3    d   32  M
4    e   23  F
5    f   20  F

In [92]:
rep.replace("M",method="ffill")

  Name  Age  C
0    a   20  M
1    b   15  F
2    c   45  F
3    d   32  F
4    e   23  F
5    f   20  F

In [94]:
rep.replace("M",method="ffill",limit=1)

  Name  Age  C
0    a   20  M
1    b   15  F
2    c   45  F
3    d   32  M
4    e   23  F
5    f   20  F

In [95]:
rep.replace("M",method="ffill",limit=1,inplace=True)

In [96]:
rep

  Name  Age  C
0    a   20  M
1    b   15  F
2    c   45  F
3    d   32  M
4    e   23  F
5    f   20  F

# Interpolate

In [98]:
int =pd.read_csv("C:\\Users\\shara\\Fill.csv")
int

  Name   Age    C
0    a  20.0  NaN
1    b  15.0    F
2    c   NaN    M
3    d   NaN    M
4    e  23.0    F
5    f  20.0    F

In [99]:
int.interpolate()

# This function only works with numbers

  Name        Age    C
0    a  20.000000  NaN
1    b  15.000000    F
2    c  17.666667    M
3    d  20.333333    M
4    e  23.000000    F
5    f  20.000000    F

In [ ]:
int.interpolate(method="")

#  method: {'linear', 'time', 'index', 'values', 'nearest', 'zero','slinear, 'quadratic', 'cubic', 'barycentric', 'krogh', 'polynomial', 'spline', 'piecewise_polynomial', 'from derivatives', 'pchip', 'akima"}

In [102]:
int.interpolate(method="linear",axis=0)

  Name        Age    C
0    a  20.000000  NaN
1    b  15.000000    F
2    c  17.666667    M
3    d  20.333333    M
4    e  23.000000    F
5    f  20.000000    F

In [105]:
int.interpolate(limit_direction="backward",limit=2)

# limit_directioncan be forward or backwardor both

  Name        Age    C
0    a  20.000000  NaN
1    b  15.000000    F
2    c  17.666667    M
3    d  20.333333    M
4    e  23.000000    F
5    f  20.000000    F

In [106]:
int.interpolate(limit_area="inside")

#limi_area can be inside or outdide

  Name        Age    C
0    a  20.000000  NaN
1    b  15.000000    F
2    c  17.666667    M
3    d  20.333333    M
4    e  23.000000    F
5    f  20.000000    F

# Merge

In [109]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

var2=pd.DataFrame({"A":[1,2,3,4],"C":[21,22,23,24]})

pd.merge(var1,var2,on="A")

   A   B   C
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [111]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

var2=pd.DataFrame({"A":[1,2,3,5],"C":[21,22,23,24]})

pd.merge(var1,var2,how="left",indicator=True)

# how can be left,right,outer,inner

   A   B     C     _merge
0  1  11  21.0       both
1  2  12  22.0       both
2  3  13  23.0       both
3  4  14   NaN  left_only

In [113]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

var2=pd.DataFrame({"A":[1,2,3,5],"B":[21,22,23,24]})

pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("name","id"))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    5   24

# Concat

In [115]:
sr1 = pd.Series([1,2,3,4])

sr2 = pd.Series([11,12,13,14])

pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [117]:
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

d2=pd.DataFrame({"A":[1,2,3,5],"C":[21,22,23,24]})

pd.concat([d1,d2],axis=1)

   A   B  A   C
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  5  24

In [119]:
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

d2=pd.DataFrame({"A":[1,2],"C":[21,22]})

pd.concat([d1,d2],axis=1,join="inner")

   A   B  A   C
0  1  11  1  21
1  2  12  2  22

In [121]:
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

d2=pd.DataFrame({"A":[1,2],"C":[21,22]})

pd.concat([d1,d2],axis=1,keys=["d1","d2"])

  d1       d2
   A   B    A     C
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

# Groupby

In [1]:
import pandas as pd

In [8]:
grp = pd.DataFrame({"Name": ["a","b","c","d","a","b","a","b","a","c","c","d"],
                    "s_1":[12,13,14,12,12,14,15,23,25,16,10,34],
                    "s_2":[23,24,25,26,27,28,29,30,25,34,35,56]})

grp

   Name  s_1  s_2
0     a   12   23
1     b   13   24
2     c   14   25
3     d   12   26
4     a   12   27
5     b   14   28
6     a   15   29
7     b   23   30
8     a   25   25
9     c   16   34
10    c   10   35
11    d   34   56

In [10]:
grp_new = grp.groupby("Name")

grp_new

In [13]:
for x,y in grp_new:
    print(x)
    print(y)

a
  Name  s_1  s_2
0    a   12   23
4    a   12   27
6    a   15   29
8    a   25   25
b
  Name  s_1  s_2
1    b   13   24
5    b   14   28
7    b   23   30
c
   Name  s_1  s_2
2     c   14   25
9     c   16   34
10    c   10   35
d
   Name  s_1  s_2
3     d   12   26
11    d   34   56

In [14]:
grp_new.get_group("a")

  Name  s_1  s_2
0    a   12   23
4    a   12   27
6    a   15   29
8    a   25   25

In [15]:
grp_new.min()

      s_1  s_2
Name
a      12   23
b      13   24
c      10   25
d      12   26

In [16]:
grp_new.max()

      s_1  s_2
Name
a      25   29
b      23   30
c      16   35
d      34   56

In [17]:
li = list(grp_new)

li

[('a',
    Name  s_1  s_2
  0    a   12   23
  4    a   12   27
  6    a   15   29
  8    a   25   25),
 ('b',
    Name  s_1  s_2
  1    b   13   24
  5    b   14   28
  7    b   23   30),
 ('c',
     Name  s_1  s_2
  2     c   14   25
  9     c   16   34
  10    c   10   35),
 ('d',
     Name  s_1  s_2
  3     d   12   26
  11    d   34   56)]

# Join

In [18]:
import pandas as pd

In [22]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]},index=["a","b","c","d"])

var2=pd.DataFrame({"C":[10,20],"D":[11,22]},index=["a","b"])

var1.join(var2)

   A   B     C     D
a  1  11  10.0  11.0
b  2  12  20.0  22.0
c  3  13   NaN   NaN
d  4  14   NaN   NaN

In [26]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]},index=["a","b","c","d"])

var2=pd.DataFrame({"C":[10,20],"D":[11,22]},index=["a","b"])

var2.join(var1,how = "right")

      C     D  A   B
a  10.0  11.0  1  11
b  20.0  22.0  2  12
c   NaN   NaN  3  13
d   NaN   NaN  4  14

In [28]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]},index=["a","b","c","d"])

var2=pd.DataFrame({"C":[10,20],"B":[11,22]},index=["a","b"])

var2.join(var1,how = "right",lsuffix="_12",rsuffix="_13")

      C  B_12  A  B_13
a  10.0  11.0  1    11
b  20.0  22.0  2    12
c   NaN   NaN  3    13
d   NaN   NaN  4    14

# Append

In [33]:
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})

var2=pd.DataFrame({"C":[10,20],"B":[11,22]})

var1.append(var2,ignore_index=True)

C:\Users\shara\AppData\Local\Temp\ipykernel_10364\1118022053.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  var1.append(var2,ignore_index=True)

     A   B     C
0  1.0  11   NaN
1  2.0  12   NaN
2  3.0  13   NaN
3  4.0  14   NaN
4  NaN  11  10.0
5  NaN  22  20.0

# Melt()

In [34]:
import pandas as pd

In [37]:
var = pd.DataFrame({"days" : [1,2,3,4,5,6],"eng" : [10,12,14,15,16,12],"maths" : [17,18,19,13,14,16]})

var

   days  eng  maths
0     1   10     17
1     2   12     18
2     3   14     19
3     4   15     13
4     5   16     14
5     6   12     16

In [69]:
pd.melt(var)

    variable value
0       days     1
1       days     1
2       days     1
3       days     1
4       days     2
5       days     2
6   std_name     a
7   std_name     b
8   std_name     a
9   std_name     a
10  std_name     b
11  std_name     b
12       eng    10
13       eng    12
14       eng    14
15       eng    15
16       eng    16
17       eng    12
18     maths    17
19     maths    18
20     maths    19
21     maths    13
22     maths    14
23     maths    16

In [70]:
pd.melt(var,id_vars=["days"],var_name="python",value_name="Pandas")

    days    python Pandas
0      1  std_name      a
1      1  std_name      b
2      1  std_name      a
3      1  std_name      a
4      2  std_name      b
5      2  std_name      b
6      1       eng     10
7      1       eng     12
8      1       eng     14
9      1       eng     15
10     2       eng     16
11     2       eng     12
12     1     maths     17
13     1     maths     18
14     1     maths     19
15     1     maths     13
16     2     maths     14
17     2     maths     16

# pivot()

In [71]:
var = pd.DataFrame({"days" : [1,2,3,4,5,6],"std_name":["a","b","a","a","b","b"],"eng" : [10,12,14,15,16,12],"maths" : [17,18,19,13,14,16]})

var

   days std_name  eng  maths
0     1        a   10     17
1     2        b   12     18
2     3        a   14     19
3     4        a   15     13
4     5        b   16     14
5     6        b   12     16

In [72]:
var.pivot(index="days",columns="std_name",values="eng")

std_name     a     b
days
1         10.0   NaN
2          NaN  12.0
3         14.0   NaN
4         15.0   NaN
5          NaN  16.0
6          NaN  12.0

In [73]:
var.pivot(index="days",columns="std_name")

           eng       maths
std_name     a     b     a     b
days
1         10.0   NaN  17.0   NaN
2          NaN  12.0   NaN  18.0
3         14.0   NaN  19.0   NaN
4         15.0   NaN  13.0   NaN
5          NaN  16.0   NaN  14.0
6          NaN  12.0   NaN  16.0

In [74]:
piv = pd.DataFrame({"days" : [1,1,1,1,2,2],"std_name":["a","b","a","a","b","b"],"eng" : [10,12,14,15,16,12],"maths" : [17,18,19,13,14,16]})

piv

   days std_name  eng  maths
0     1        a   10     17
1     1        b   12     18
2     1        a   14     19
3     1        a   15     13
4     2        b   16     14
5     2        b   12     16

In [75]:
piv.pivot_table(index="std_name",columns="days",
                aggfunc="mean")

           eng            maths
days         1     2          1     2
std_name
a         13.0   NaN  16.333333   NaN
b         12.0  14.0  18.000000  15.0

In [76]:
piv.pivot_table(index="std_name",columns="days",
                aggfunc="sum",margins="True")

           eng           maths
days         1     2 All     1     2 All
std_name
a         39.0   NaN  39  49.0   NaN  49
b         12.0  28.0  40  18.0  30.0  48
All       51.0  28.0  79  67.0  30.0  97